/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124070-g75838b9c89-20260421"
#endif /* AVUTIL_FFVERSION_H */
